### ISSUE TITLE
Error code:0x80070002

### ISSUE THREAD

**Issue by N9i9n9e** [REVIPED/FPSUnlocker#2]
i can`t use fpsunlocker,when i run RBXFPS,he said An internal error occured while importing modules

**Comment by Tom-Roblox** [comment]
![ScreenShot_20230626095728](https://github.com/REVIPED/FPSUnlocker/assets/137804484/147063f8-4cf0-4e9b-b92e-23e8f1dd94e5)
I have the same problem to
